date_range:
  datetime_str: '%Y-%m-%d %H:%M:%S'
  end: '2019-03-22 00:00:00'
  start: '2019-03-21 00:00:00'
db_request_name: 'expt_file_counts'
method: 'GET'
experiments:
- graph_color: 'black'
  graph_label: 'Number of files'
  name: 'replay spinup stream 4'
  wallclock_start: '2023-01-01 00:00:00'
fig_base_fn: 'file_counts'
stat_groups:
- cycles:
  - 0
  - 21600
  - 43200
  - 64800
  metrics:
  - count
  stat_group_frmt_str: file_{metric}
work_dir: /contrib/Adam.Schneider/replay/results
