date_range:
  datetime_str: '%Y-%m-%d %H:%M:%S'
  end: '2019-03-21 00:00:00'
  start: '2016-03-22 00:00:00'
db_request_name: plot_file_counts
experiments:
- graph_color: [INSERT COLOR]
  graph_label: [INSERT LABEL]
  name: [INSERT EXPERIMENT NAME]
  wallclock_start: '2023-01-01 00:00:00'
- graph_color: [INSERT COLOR]
  graph_label: INSERT LABEL]
  name: INSERT EXPERIMENT NAME]
  wallclock_start: '2023-01-02 00:00:00'
fig_base_fn: [INSERT FIGURE FILENAME]
stat_groups:
- cycles:
  - 0
  - 21600
  - 43200
  - 64800
  metrics:
  - count
  stat_group_frmt_str: file_{metric}
work_dir: /contrib/Adam.Schneider/replay/results